### ISSUE TITLE
No access to bitbucket

### ISSUE THREAD

**Issue by kiarafbickers** [NoahDragon/hexo-theme-react#3]
$ git clone git@bitbucket.org:l3z/hexo-theme-react.git themes/react
Cloning into 'themes/react'...

git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by raphael-liu** [comment]
same issue

**Comment by jimbobshazham** [comment]
I'm running into the same issue here also.

**Comment by NoahDragon** [comment]
This project is migrated from bitbucket, but forgot to change the README file. Please use the following command instead:
```
git clone https://github.com/NoahDragon/hexo-theme-react.git themes/react
```
